name: Laravel

on:
  push:
    branches: [ master, chore-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

  deploy:
    needs: laravel-tests

    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Install Node.js dependencies and minifies JS/CSS files
      run: npm install && npm run prod

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: ${{ secrets.SERVER_DIR }}
        log-level: minimal
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - README.md
          - composer*.json
          - package*.json
          - phpunit.xml
          - node_modules/@*
          - node_modules/a*
          - node_modules/b*
          - node_modules/c*
          - node_modules/d*
          - node_modules/e*
          - node_modules/f*
          - node_modules/g*
          - node_modules/h*
          - node_modules/i*
          - node_modules/j*
          - node_modules/k*
          - node_modules/l*
          - node_modules/m*
          - node_modules/n*
          - node_modules/o*
          - node_modules/p*
          - node_modules/q*
          - node_modules/r*
          - node_modules/s*
          - node_modules/t*
          - node_modules/u*
          - node_modules/v*
          - node_modules/w*
          - node_modules/x*
          - node_modules/@*
          - vendor/a*
          - vendor/b*
          - vendor/c*
          - vendor/d*
          - vendor/e*
          - vendor/f*
          - vendor/g*
          - vendor/h*
          - vendor/i*
          - vendor/j*
          - vendor/k*
          - vendor/l*
          - vendor/m*
          - vendor/n*
          - vendor/o*
          - vendor/p*
          - vendor/q*
          - vendor/r*
          - vendor/s*
          - vendor/t*
          - vendor/u*
          - vendor/v*
          - vendor/w*
          - vendor/x*
